// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7hXe4RXypzZBabOoxU-5UkZe7ZrN6Oyk',
    appId: '1:319785575667:web:90bf294da1cfa7a21f4386',
    messagingSenderId: '319785575667',
    projectId: 'kenz-fashion-d060d',
    authDomain: 'kenz-fashion-d060d.firebaseapp.com',
    storageBucket: 'kenz-fashion-d060d.firebasestorage.app',
    measurementId: 'G-D46NLMBWCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZtIbg_uXEGNocq6JwE8hZUsDVe28MypU',
    appId: '1:319785575667:android:0d4e39ad8a711c7d1f4386',
    messagingSenderId: '319785575667',
    projectId: 'kenz-fashion-d060d',
    storageBucket: 'kenz-fashion-d060d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgEnMjcsTRO6IP0cT1MjLPmY8RDlQfTX8',
    appId: '1:319785575667:ios:18983caa921872f41f4386',
    messagingSenderId: '319785575667',
    projectId: 'kenz-fashion-d060d',
    storageBucket: 'kenz-fashion-d060d.firebasestorage.app',
    iosClientId: '319785575667-lgmk9chh1lat6gpi1spnkto3jvtfu11l.apps.googleusercontent.com',
    iosBundleId: 'com.example.dijab',
  );
}
